# Generated by Django 4.0.4 on 2023-02-24 21:19

import chat_module.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_module', '0002_chat_alter_member_chat_alter_message_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_seen',
            field=models.BooleanField(default=False, verbose_name='سین شده'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='unique_code',
            field=models.CharField(default=chat_module.models.unique_generator, max_length=10, unique=True),
        ),
    ]
