# Generated by Django 4.0.4 on 2023-03-02 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_module', '0004_filemessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileMessage',
            new_name='ImageMessage',
        ),
    ]
