# Generated by Django 4.0.4 on 2023-03-02 04:15

from django.db import migrations, models
import django.db.models.deletion
import utils.unique_code_generator


class Migration(migrations.Migration):

    dependencies = [
        ('chat_module', '0005_rename_filemessage_imagemessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/chat')),
                ('unique_code', models.CharField(default=utils.unique_code_generator.id_generator, editable=False, max_length=10, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat_module.message')),
            ],
        ),
    ]
