# Generated by Django 4.0.2 on 2022-05-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'اعلان', 'verbose_name_plural': 'اعلان ها'},
        ),
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='زمان قرار گیری اعلان'),
        ),
        migrations.AddField(
            model_name='notification',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='ساعت قرار کیری اعلان'),
        ),
    ]
