# Generated by Django 4.0.2 on 2022-05-27 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_module', '0018_alter_lesson_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification_module', '0003_notification_home_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='زمان قرار گیری اعلان')),
                ('time', models.TimeField(auto_now_add=True, null=True, verbose_name='ساعت قرار کیری اعلان')),
                ('text', models.TextField(verbose_name='متن اعلان')),
                ('is_read', models.BooleanField(verbose_name='خوانده شده')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_teacher', to=settings.AUTH_USER_MODEL, verbose_name='از طرف')),
                ('home_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_home_work', to='lesson_module.sethomework', verbose_name='مربوط به تکلیف')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربران')),
            ],
        ),
    ]
