# Generated by Django 4.0.2 on 2022-05-27 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification_module', '0004_notifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
