# Generated by Django 4.0.4 on 2022-09-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_module', '0006_customnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customnotification',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='متن اعلان'),
        ),
    ]
