# Generated by Django 4.0.4 on 2022-09-20 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0077_alter_base_title_alter_fieldofstudy_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='موضوع ایمیل')),
                ('content', models.TextField(verbose_name='متن ایمیل')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_base', to='lessons.base', verbose_name='برای به پایه')),
                ('field_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_field_of_study', to='lessons.fieldofstudy', verbose_name='برای به رشته')),
                ('from_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_sender', to=settings.AUTH_USER_MODEL, verbose_name='از طرف معلم')),
            ],
        ),
        migrations.CreateModel(
            name='LinkEmailFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/email')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='send_email_module.email', verbose_name='برای ایمیل')),
            ],
        ),
    ]
