# Generated by Django 4.0.4 on 2022-09-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_email_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='send_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ارسال در تاریخ'),
        ),
    ]
