# Generated by Django 4.0.2 on 2022-05-06 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_sitesetting_nmd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='nmd',
        ),
    ]
