# Generated by Django 4.0.2 on 2022-05-06 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_module', '0007_lessons'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lessons',
        ),
    ]
