# Generated by Django 4.0.2 on 2022-05-06 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesson_module', '0008_delete_lessons'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetHomeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان تکلیف')),
                ('start_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت تکلیف')),
                ('end_at', models.DateTimeField(verbose_name='تاریخ پایان مهلت تکلیف')),
                ('description', models.TextField(verbose_name='توضیحات تکلیف')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_module.lesson', verbose_name='مربوط به درس')),
                ('teacher', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='معلم')),
            ],
        ),
        migrations.CreateModel(
            name='HomeWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('file', models.FileField(upload_to='files/home_works', verbose_name='تکلیف ارسال شده')),
                ('home_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_module.sethomework', verbose_name='مربوط به تکلیف')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='دانش آموز')),
            ],
        ),
    ]
