# Generated by Django 4.0.2 on 2022-05-06 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_module', '0010_alter_homeworks_options_alter_sethomework_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworks',
            name='home_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taklif', to='lesson_module.sethomework', verbose_name='مربوط به تکلیف'),
        ),
    ]
