# Generated by Django 4.0.2 on 2022-05-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_module', '0011_alter_homeworks_home_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='nmd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/home_works')),
            ],
        ),
    ]
