# Generated by Django 4.0.2 on 2022-05-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_module', '0012_nmd'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworks',
            name='is_delivered',
            field=models.BooleanField(default=False, verbose_name='وضعیت تحویل'),
        ),
    ]
