# Generated by Django 4.0.2 on 2022-05-06 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_module', '0013_homeworks_is_delivered'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nmd',
        ),
    ]
