# Generated by Django 4.0.2 on 2022-06-08 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_module', '0018_alter_lesson_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='slug',
        ),
    ]
