# Generated by Django 4.0.4 on 2022-06-23 06:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_module', '0019_remove_lesson_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworks',
            name='file',
            field=models.FileField(upload_to='files/home_works', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='تکلیف ارسال شده'),
        ),
    ]
