# Generated by Django 4.0.4 on 2022-06-23 06:49

from django.db import migrations, models
import utils.file_validator


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_module', '0021_alter_homeworks_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworks',
            name='file',
            field=models.FileField(upload_to='files/home_works', validators=[utils.file_validator.FileValidator(content_types=('application/pdf',), max_size=102400)], verbose_name='تکلیف ارسال شده'),
        ),
    ]
