# Generated by Django 4.0.4 on 2022-06-25 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0050_allowedformats_alter_fieldofstudy_title'),
        ('lesson_module', '0023_alter_homeworks_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='sethomework',
            name='allowed_formats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.allowedformats', verbose_name='فرمت های مجاز'),
        ),
    ]
