# Generated by Django 4.0.4 on 2022-06-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0051_alter_allowedformats_options_and_more'),
        ('lesson_module', '0024_sethomework_allowed_formats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sethomework',
            name='allowed_formats',
        ),
        migrations.AddField(
            model_name='sethomework',
            name='allowed_formats',
            field=models.ManyToManyField(blank=True, null=True, related_name='allowed_formats', to='lessons.allowedformats', verbose_name='فرمت های مجاز'),
        ),
    ]
