# Generated by Django 4.0.4 on 2022-06-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_module', '0025_remove_sethomework_allowed_formats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sethomework',
            name='max_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر اندازه فایل(mb)'),
        ),
    ]
