# Generated by Django 4.0.4 on 2022-06-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_module', '0026_sethomework_max_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sethomework',
            name='max_size',
            field=models.FloatField(blank=True, null=True, verbose_name='حداکثر اندازه فایل(mb)'),
        ),
    ]
