# Generated by Django 4.0.4 on 2022-06-25 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_module', '0027_alter_sethomework_max_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWorkFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/home_works', verbose_name='فایل تکلیف')),
                ('home_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_module.homeworks', verbose_name='مربوط به تکلیف')),
            ],
        ),
    ]
