# Generated by Django 4.0.4 on 2022-06-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_module', '0028_homeworkfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworks',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/home_works', verbose_name='تکلیف ارسال شده'),
        ),
    ]
