# Generated by Django 4.0.4 on 2022-06-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_module', '0030_alter_homeworkfiles_options_remove_homeworks_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sethomework',
            name='start_at',
            field=models.DateTimeField(verbose_name='تاریخ شروع تکلیف'),
        ),
    ]
