# Generated by Django 4.0.4 on 2022-06-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_module', '0031_alter_sethomework_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sethomework',
            name='start_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت تکلیف'),
        ),
    ]
