# Generated by Django 4.0.4 on 2022-06-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0059_alter_base_title_alter_fieldofstudy_title'),
        ('lesson_module', '0032_alter_sethomework_start_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='poodeman_or_nobat',
            field=models.CharField(choices=[('poodeman', 'پودمانی'), ('nobat', 'نوبتی')], default='poodeman', max_length=20, verbose_name='نوع درس'),
        ),
        migrations.AlterField(
            model_name='sethomework',
            name='allowed_formats',
            field=models.ManyToManyField(blank=True, related_name='allowed_formats', to='lessons.allowedformats', verbose_name='فرمت های مجاز'),
        ),
    ]
