# Generated by Django 4.0.4 on 2022-06-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_module', '0034_poodemanandnobat_sethomework_poodeman_or_nobat'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworks',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='نمره تکلیف'),
        ),
        migrations.AddField(
            model_name='sethomework',
            name='score_weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='وزن نمره'),
        ),
    ]
