# Generated by Django 4.0.4 on 2022-07-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_module', '0036_poodemanandnobat_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poodemanandnobat',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, null=True, unique=True, verbose_name='عنوان در url'),
        ),
    ]
