# Generated by Django 4.0.4 on 2022-07-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_module', '0037_alter_poodemanandnobat_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworks',
            name='score_percent',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='درصد نمره'),
        ),
    ]
