# Generated by Django 4.0.2 on 2022-05-06 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_base_title_alter_fieldofstudy_title'),
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.base', verbose_name='پایه دانش آموز'),
        ),
        migrations.AddField(
            model_name='user',
            name='field_of_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.fieldofstudy', verbose_name='رشته'),
        ),
    ]
