# Generated by Django 4.0.2 on 2022-05-06 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('lessons', '0005_alter_base_title_alter_fieldofstudy_title'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account_module', '0003_rename_user_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
