# Generated by Django 4.0.4 on 2022-09-21 05:30

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0012_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AddField(
            model_name='user',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[utils.validators.is_valid_iran_code], verbose_name='کد ملی'),
        ),
    ]
