# Generated by Django 4.0.2 on 2022-05-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='title',
            field=models.CharField(choices=[('paye_12', 'پایه دوازدهم'), ('paye_10', 'پایه دهم'), ('paye_11', 'پایه یازدهم')], default='paye_10', max_length=50, verbose_name='عنوان پایه'),
        ),
        migrations.AlterField(
            model_name='fieldofstudy',
            name='title',
            field=models.CharField(choices=[('Experimental_Science', 'علوم تجربی'), ('Liberal_Arts', 'علوم انسانی'), ('Mathematical_Physics', 'ریاضی فیزیک'), ('Software_Defined_Networking', 'شبکه و نرم افزار')], max_length=50, verbose_name='عنوان رشته تحصیلی'),
        ),
    ]
