# Generated by Django 4.0.4 on 2022-06-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0049_alter_base_title_alter_fieldofstudy_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedFormats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=100, verbose_name='فرمت')),
            ],
        ),
        migrations.AlterField(
            model_name='fieldofstudy',
            name='title',
            field=models.CharField(choices=[('Mathematical_Physics', 'ریاضی فیزیک'), ('Software_Defined_Networking', 'شبکه و نرم افزار'), ('Experimental_Science', 'علوم تجربی'), ('Liberal_Arts', 'علوم انسانی')], max_length=50, verbose_name='عنوان رشته تحصیلی'),
        ),
    ]
