# Generated by Django 4.0.4 on 2022-06-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0054_alter_base_title_alter_fieldofstudy_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='title',
            field=models.CharField(choices=[('paye_10', 'پایه دهم'), ('paye_12', 'پایه دوازدهم'), ('paye_11', 'پایه یازدهم')], default='paye_10', max_length=50, verbose_name='عنوان پایه'),
        ),
        migrations.AlterField(
            model_name='fieldofstudy',
            name='title',
            field=models.CharField(choices=[('Liberal_Arts', 'علوم انسانی'), ('Software_Defined_Networking', 'شبکه و نرم افزار'), ('Experimental_Science', 'علوم تجربی'), ('Mathematical_Physics', 'ریاضی فیزیک')], max_length=50, verbose_name='عنوان رشته تحصیلی'),
        ),
    ]
