# Generated by Django 4.0.4 on 2023-02-25 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0084_alter_base_title_alter_fieldofstudy_title'),
        ('lessons', '0087_alter_base_title_alter_fieldofstudy_title'),
    ]

    operations = [
    ]
