# Generated by Django 4.0.4 on 2023-02-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0088_merge_20230225_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='title',
            field=models.CharField(choices=[('paye_11', 'پایه یازدهم'), ('paye_10', 'پایه دهم'), ('paye_12', 'پایه دوازدهم')], default='paye_10', max_length=50, verbose_name='عنوان پایه'),
        ),
        migrations.AlterField(
            model_name='fieldofstudy',
            name='title',
            field=models.CharField(choices=[('Mathematical_Physics', 'ریاضی فیزیک'), ('Experimental_Science', 'علوم تجربی'), ('Liberal_Arts', 'علوم انسانی'), ('Software_Defined_Networking', 'شبکه و نرم افزار')], max_length=50, verbose_name='عنوان رشته تحصیلی'),
        ),
    ]
