# Generated by Django 4.0.4 on 2022-09-09 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0074_alter_base_title_alter_fieldofstudy_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=30, verbose_name='عنوان سوال')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_base', to='lessons.base', verbose_name='برای پایه')),
                ('field_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_fieldofstudy', to='lessons.fieldofstudy', verbose_name='برای رشته')),
                ('from_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_teacher', to=settings.AUTH_USER_MODEL, verbose_name='از طرف معلم')),
                ('users', models.ManyToManyField(blank=True, related_name='poll_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربران')),
            ],
            options={
                'verbose_name': 'نظرسنجی',
                'verbose_name_plural': 'نظرسنجی ها',
                'ordering': ('-create',),
            },
        ),
        migrations.CreateModel(
            name='PollOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=30, verbose_name='گزینه')),
                ('option_count', models.IntegerField(default=0, verbose_name='شمارش گزینه')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_option', to='poll_module.poll', verbose_name='برای نظرسنجی')),
            ],
            options={
                'verbose_name': 'گزینه',
                'verbose_name_plural': 'گزینه ها',
            },
        ),
    ]
